### PR TITLE
Upgrading NPM-based packages (stdenv.lib deprecation issue)

### PR DESCRIPTION
**Pull request by toastal**
@justinwoo It seems the what were warnings about `stdenv.lib`  are now fully deprecated in Nix Unstable. I was getting errors where I could no longer use my devShell. Rather just removing `stdenv` (as the code suggest to not modify those generated files), I ran the latest `node2nix` (`1.8.0 -> 1.9.0`) on the Node packages again update all dependencies and have a consistent `node2nix` being used. It has been a long time since these NPM package versions have been updated possibly missing out on security and performance improvements.

### CODE REVIEW

**Comment by jamesdbrock** [comment]
@toastal How did you generate these files? Cloning `pulp` and running `node2nix --nodejs-12 --lock package-lock.json` produces 

```
# This file has been generated by node2nix 1.9.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-12_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile writeShellScript;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv;
}
```

but when you ran some command you produced

```
# This file has been generated by node2nix 1.9.0. Do not edit!

{ pkgs ? import <nixpkgs> {
    inherit system;
  }
, system ? builtins.currentSystem
, nodejs ? pkgs."nodejs-12_x"
}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };

  nodePackage = import ./node-packages.nix
    {
      inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
      inherit nodeEnv;
    };

  source = nodePackage.sources."pulp-15.0.0".src;
in
nodeEnv.buildNodePackage (nodePackage.args // { src = source; })
```

What command did you run?

**Comment by jamesdbrock** [comment]
I'm guessing that what you did is run `node2nix --lock package-lock.json` in a clone of the `pulp` repo because that's the only way to use the `package-lock.json`. https://github.com/svanderburg/node2nix/issues/132 And then you edited the generated `default.nix`.

**Comment by toastal** [comment]
Hi. So what I have been doing is keeping an uncommitted `package.json` around the folders. For instance this in `purs-tidy`:

```json
{
  "name": "purs-tidy",
  "version": "0.7.1",
  "dependencies": {
    "purs-tidy": "0.7.1"
  }
}
```

When I new version comes in, I bump these numbers to match the NPM release. Following this I just run `node2nix` with the latest `node2nix` version (Node v12 is deprecated, and `node2nix` seems to favor the latest maintenance version instead of latest LTS).

After `node2nix` does it's thing. I run `git checkout` on the `default.nix` to keep the modifications Justin did way back when. Then I go back and `nvim default.nix` and edit the version number to match the `package.json` and generated code.

I `git add *.nix`, `git commit` and write my merge request message, then `git push github $BRANCH`. The diff this creates is usually minimal which Justin tends to approve of in <48 hours because it's just a few version bumps to read on his end.

**Comment by jamesdbrock** [comment]
Thanks @toastal . I think I'm going to try to write an import-from-derivation derivation so that we don't have to keep an uncommited `package.json` lying around.

**Comment by toastal** [comment]
That sounds good. This is what I was doing that "just worked" and kept the diffs small.

**Pull request merged**
