### PR TITLE
Add pscid

### PR DESCRIPTION
**Pull request by jmackie**

### CODE REVIEW

**Comment by justinwoo** [comment]
Looks like some kind of expression didn't evaluate. I never use npm packages via Nix, so I don't really know what to expect either.

One thing that would be nice to address for anyone consumign this would be to fix usage of Node 6.x, which is EOL this month: https://github.com/nodejs/Release#release-schedule

**Comment by jmackie** [comment]
My bad, I should have run the tests before opening the PR. Also my bad on the old Node version - I kept getting a weird error that turned out to be because `node2nix` targets specific versions (v6 by default, apparently).

**Comment by justinwoo** [comment]
Hopefully the node2nix people know to update to v10 asap...

**Comment by justinwoo** [comment]
Thanks

**Comment by jmackie** [comment]
https://github.com/svanderburg/node2nix/issues/140 :+1:

**Pull request merged**
