### PR TITLE
Updates pinned packages + pscid dependencies

### PR DESCRIPTION
**Pull request by jkachmar**
So it looks like I was wrong in #108 and there were actually some dep updates. I figured as long as I was updating those deps I might as well updated the pinned nixpkgs here and source the `node-env` from that same set of pinned packages as well.

I updated everything in a way that seemed to make sense and then the build started failing for no discernible reason:

```
builder for '/nix/store/zqi7mbxrl7d6kbaj6il42zxk8p1pkh73-node_pscid-2.9.2.drv' failed with exit code 1; last 10 log lines:
  lodash@4.17.15 /nix/store/jcva1lwqj1vaffrmznibkqq1v9qr3f0p-node_pscid-2.9.2/lib/node_modules/pscid/node_modules/lodash
  keypress@0.2.1 /nix/store/jcva1lwqj1vaffrmznibkqq1v9qr3f0p-node_pscid-2.9.2/lib/node_modules/pscid/node_modules/keypress
  which@2.0.2 /nix/store/jcva1lwqj1vaffrmznibkqq1v9qr3f0p-node_pscid-2.9.2/lib/node_modules/pscid/node_modules/which
  isexe@2.0.0 /nix/store/jcva1lwqj1vaffrmznibkqq1v9qr3f0p-node_pscid-2.9.2/lib/node_modules/pscid/node_modules/isexe
  npm ERR! code ENOTCACHED[35mlifecycle pscid@2.9.2~preinstall:
  npm ERR! request to https://registry.npmjs.org/gaze failed: cache mode is 'only-if-cached' but no cached response available.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /private/tmp/nix-build-node_pscid-2.9.2.drv-0/.npm/_logs/2020-06-19T05_26_18_208Z-debug.log
```

Seems like this was being caused by whatever tarball is on the npmjs.org registry so I swapped it over to pulling from [the GitHub source](https://github.com/kritzcreek/pscid) as of the 2.9.2 release.

I've gone ahead and incorporated the changes that were in #109 here just to have a centralized PR that should clean up this shit.

### CODE REVIEW

**Comment by jkachmar** [comment]
No idea why `zephyr` is failing, it works locally:
```
jkachmar in easy-purescript-nix on <updates-pins> took 5m41s ❯ nix-shell

[nix-shell:~/src/easy-purescript-nix]$ $(which zephyr) --version
0.3.1
```

**Comment by justinwoo** [comment]
You were missing zephyr build input

**Comment by justinwoo** [comment]
> Seems like this was being caused by whatever tarball is on the npmjs.org registry so I swapped it over to pulling from the GitHub source as of the 2.9.2 release.

this doesn't work because publishing workflows of npm mean that published versions of packages uploaded to npm are not the same as the source input. you can very clearly see that one of the many errors you get will be this:

```
/nix/store/m7q2wmaj47dkhkc0sz9alxq3fcn0y1zy-node_pscid-2.9.2/bin/pscid
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './output/Main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/nix/store/m7q2wmaj47dkhkc0sz9alxq3fcn0y1zy-node_pscid-2.9.2/lib/node_modules/pscid/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

look at what is defined for prepack in pscid: https://github.com/kritzcreek/pscid/blob/e497ccb059261cce522bed5401538b7027c59fb4/package.json#L14

and look at the documentation in npm: https://docs.npmjs.com/misc/scripts

this is only a part of why consuming npm packages is such a nightmare

**Comment by justinwoo** [comment]
https://github.com/justinwoo/easy-purescript-nix/runs/787698638?check_suite_focus=true#step:4:707

**Comment by justinwoo** [comment]
Fixed this by just rewriting the pscid derivations. It should now be fairly obvious what needs to be done to update this shit for anyone looking at the source

**Pull request merged**
