### PR TITLE
script to update packages

### LINKED ISSUE #46: script to update packages
add scripts to update packages

e.g. I always add `update.sh` script to update `revision.json`/other logic

example https://github.com/srghma/dotfiles/blob/master/nixos/pkgs/dunsted-volume/update.sh

this way I dont need to look for new commit, paste it in nix file, make `nix-build`, then update expected hash

I just run `update.sh` and that's all

____________

Why I suggest this:
1. to allewiate steps above
2. there is no info how pscid is generated and how to update it

N.B. it would be good to have some script `update-everything.sh` that would run all `update.sh` scripts in repo

### PR DESCRIPTION
**Pull request by srghma**
fixes #46

### CODE REVIEW

**Comment by srghma** [comment]
related https://github.com/justinwoo/easy-purescript-nix/issues/48

**Comment by srghma** [comment]
@justinwoo can we remove purs package since purs binary is exported from purescript package in nixpkgs?

**Comment by justinwoo** [comment]
No, that would defeat the purpose of this project.

**Comment by srghma** [comment]
> No, that would defeat the purpose of this project.

will you leave spago in this repo and maintain even if it would be added to nixpkgs? (as stated in this issue https://github.com/justinwoo/easy-purescript-nix/issues/49 ). Just wondering

**Comment by justinwoo** [comment]
Yes, I will, because I use it directly myself and update it as I need to.

**Comment by srghma** [comment]
I think I'm done for now, I dont use other packages

**Comment by justinwoo** [comment]
Looks like it quits early when trying to do something here: https://travis-ci.com/justinwoo/easy-purescript-nix/builds/113805351#L533-L538

**Comment by srghma** [comment]
@justinwoo what about spacchetti-cli? https://github.com/justinwoo/spacchetti-cli redirects to https://github.com/spacchetti/spago

**Comment by srghma** [comment]
@justinwoo what about zephyr - it has it's own derivation https://github.com/coot/zephyr/blob/master/pkg.nix ?

**Comment by justinwoo** [comment]
I use the zephyr derivation still, you'll see that this project routinely bundles other packages.

Spacchetti-CLI is the old version of spago, so it can be removed

**Comment by justinwoo** [comment]
I just looked at the zephyr derivation and I would not consume it in that way, so I will keep the derivation here for my uses

**Comment by srghma** [comment]
just found that purescript package in nixpkgs is the exact copy of purscript here, thats cool))

**Comment by srghma** [comment]
@justinwoo the pscid will be updated https://github.com/kRITZCREEK/pscid/issues/52 and the travis ci fixed, apart from that everything else build, maybe we could merge it?

**Comment by srghma** [comment]
added update scripts to all packages, removed spacchetti-cli

**Comment by justinwoo** [comment]
Sorry, but this tries to rewrite everything in terms of importing some constants from a JSON file? I also do not want to also inherit a bunch of bash scripts to do updating on these. I hope you'll understand that I do not want to merge this PR in this form.

**Comment by srghma** [comment]
@justinwoo how do you propose to update packages then?

**Comment by justinwoo** [comment]
I don't want to try to argue every little thing, but I update packages in a typical old fashioned way: users use whatever programs or scripts they have on their own computers to update the string literals for URLs and SHAs, which are then to be tested by CI.

**Comment by srghma** [comment]
anyway, please dont close this pr, I want users to see this and make their own decisions

(I will try to keep packages this updated)

**Comment by srghma** [comment]
btw, the advantage of this approach is that you can write systemd script that runs all `update.sh` scripts once in a day and pushes changes to master automatically

**Comment by justinwoo** [comment]
I will close this PR because I don't want to keep PRs that can't be merged open here. The same judgment applies to my other PR.

**Comment by srghma** [comment]
@justinwoo what would you say about https://github.com/justinwoo/easy-purescript-nix/pull/50#issuecomment-498156734

**Pull request closed without merging**
