### PR TITLE
Re-add purty

### PR DESCRIPTION
**Pull request by paluh**
We are using npm registry as a binary source for pury.

### CODE REVIEW

**Comment by paluh** [comment]
Fixes #140

**Comment by toastal** [comment]
Do we know of the sustainability of this? We can rely on it being published here as well?

**Comment by paluh** [comment]
@toastal, as @justinwoo pointed [here](https://github.com/justinwoo/easy-purescript-nix/issues/140#issuecomment-847061128) there are [multiple places which use npm registry as a source of binaries](https://github.com/justinwoo/easy-purescript-nix/search?q=npmjs). Additionally it seems that purty releasing strategy incorporates npm publishing [as one of its steps](https://gitlab.com/joneshf/purty/-/blob/master/Makefile#L82).

Could you please tell me if that answers your question, because I'm not sure if these two points proof any "sustainability" really ;-)

**Comment by toastal** [comment]
Ah, I meant do we know that `purty` will continue publishing there, but I guess it's a nonissue because 'now' is what matters. Nevermind 😅

**Comment by justinwoo** [comment]
could you fix the test?

**Comment by paluh** [comment]
Sorry, I'm not sure how I was able to miss ci result. Done ;-)

**Comment by justinwoo** [comment]
thanks

**Pull request merged**
