### PR TITLE
Update pscid (WIP)

### LINKED ISSUE #48: Build fails due to pscid bower packages
@jmackie could you fix this issue?

### PR DESCRIPTION
**Pull request by vyorkin**
Depends on https://github.com/kRITZCREEK/pscid/issues/52

closes #48

### CODE REVIEW

**Comment by justinwoo** [comment]
master of pscid should now be updated for purescript 0.13.0, so try doing this again using the master SHA

**Comment by vyorkin** [comment]
I've just tried it on my machine, but I keep getting the following error:
```
bower purescript-psa-utils#^5.1.0            ENOCACHE No cached version for https://github.com/natefaubion/purescript-psa-utils.git#^5.1.0
```

**Comment by justinwoo** [comment]
sounds icky. let me see what i can do with a fork of pscid

**Comment by justinwoo** [comment]
here's a tag that has spago build and doesn't require rebuilding the purescript part, so hopefully just hooking up node2nix should make this work fine: https://github.com/justinwoo/pscid/releases/tag/2019-06-18-spago

**Comment by vyorkin** [comment]
Now I have the following error:
```
▲ /nix/store/9kxfm9l6x8w53fgsmhajazwxblxfrlzw-node-pscid-2.6.0 pscid
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
```

**Comment by justinwoo** [comment]
ah,sorry, that's some mess up on my end

**Comment by justinwoo** [comment]
sorry, i think i have finally fixed my pscid reference. let's see if this works

**Comment by justinwoo** [comment]
nice, looks to be in order. thanks!

**Pull request merged**
