### PR TITLE
Use pname

### PR DESCRIPTION
**Pull request by kayhide**
With `pname`, a package name is automatically versioned.

```console
$ nix-env -f . -iA purs
installing 'purescript-0.13.5'
...

$ nix-env -f . -iA spago
installing 'spago-0.10.0.0'
...

$ nix-env -q | grep "purescript\|spago"
purescript-0.13.5
spago-0.10.0.0
```

### CODE REVIEW

**Comment by justinwoo** [comment]
I don't use this form since I keep everything in literal form to make it easier to update automatically and easier to search through

**Comment by justinwoo** [comment]
maybe worth using `pname` though. one thing i'd like to make sure though is that you can always replace your current profile's older purescript version with a newer one though, but i could test that manually

**Comment by kayhide** [comment]
Hi @justinwoo , thanks for your consideration.

I am not sure I understand your point but, even if the package name is versioned, you can still update it automatically.

Let's assume that you already have older version in your nix profile:

```console
$ nix-env -q | grep purescript
purescript-0.13.4
```

Then update your local clone of `easy-purescript-nix` repo and try to hit the same command:

```console
$ nix-env -f . -iA purs
replacing old 'purescript-0.13.4'
installing 'purescript-0.13.5'
```

I imagine that this is the behavior you wanted, right?

**Comment by justinwoo** [comment]
yup, that sounds good

**Comment by kayhide** [comment]
@justinwoo Hi, how is it going?
I just rebased the branch onto the current master.

So, what would you like to do with this PR?
Is there any other reason not to use `pname`?

**Comment by justinwoo** [comment]
It's probably fine. I don't like using the `version` attribution or string interpolation, but we can just merge this as is for now. Thanks

**Comment by kayhide** [comment]
Okay, great!
Thanks for accepting my PR!

**Pull request merged**
